##### BEGIN image/Dockerfile/image-header #####
FROM vcwebio/conteco.docs.base AS base
##### END image/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####

##### END image/Dockerfile/build-instructions #####

##### BEGIN image/Dockerfile/env-labels-footer #####
ENV CONTECO_NAME="overview" \
    CONTECO_TAG="v1.0.0" \
    CONTECO_BASE="docs.base" \
    CONTECO_BUILD="image"
LABEL io.vcweb.name="overview" \
      io.vcweb.tag="v1.0.0" \
      io.vcweb.base="docs.base" \
      io.vcweb.build="image" \
      io.vcweb.label="Overview Documentation" \
      io.vcweb.description="An overview of the orchestratin platform." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.docs.overview --help" 
##### END image/Dockerfile/env-labels-footer #####
