##### BEGIN image/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS base
##### END image/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
##### END image/Dockerfile/build-instructions #####

##### BEGIN image/Dockerfile/env-labels-footer #####
ENV CONTECO_TYPE="docs" \
    CONTECO_NAME="overview" \
    CONTECO_TAG="v1.0.2" \
    CONTECO_BASE="image.wrapper" \
    CONTECO_BUILD="image"
LABEL io.vcweb.type="docs" \
      io.vcweb.name="overview" \
      io.vcweb.tag="v1.0.2" \
      io.vcweb.base="image.wrapper" \
      io.vcweb.build="image" \
      io.vcweb.label="docs.overview - vcWEB Platform" \
      io.vcweb.description="vcWEB Platform: Building Solutions from Container and Module Ecosystems" \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.docs.overview --help"
##### END image/Dockerfile/env-labels-footer #####
