#!/usr/bin/env bash

export CONTECO_LABEL="Conteco Documentation base image"
export CONTECO_DESCRIPTION="The base for Conteco documentation image."

export CONTECO_TYPE="docs"
export CONTECO_NAME="base"
export CONTECO_TAG="v1.0.0"

export CONTECO_BASE="image.base"
export CONTECO_BUILD="image-base"
