#!/usr/bin/env bash

export CONTECO_LABEL="docs.overview - vcWEB Platform"
export CONTECO_DESCRIPTION="vcWEB Platform: Building Solutions from Container and Module Ecosystems"

export CONTECO_TYPE="docs"
export CONTECO_NAME="overview"
export CONTECO_TAG="v1.0.2"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
