---
version: '3'
services:

# START SERVICE docs.overview
  docs:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.${CONTECO_DC_GLOBAL_IMAGE_NAME}
    environment: [${CONTECO_DC_DOCS_ENVIRONMENT}]
    command: [${CONTECO_DC_DOCS_COMMAND}]
    volumes: [${CONTECO_DC_DOCS_VOLUMES}]
    ports: [${CONTECO_DC_DOCS_PORTS}]
    networks: [${CONTECO_DC_DOCS_NETWORKS}]
    deploy:
      mode: ${CONTECO_DC_DOCS_DEPLOY_MODE}
      resources:
        limits:
          memory: '${CONTECO_DC_DOCS_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${CONTECO_DC_DOCS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${CONTECO_DC_DOCS_COMPOSE_EXTENSIONS}
# END SERVICE docs.overview

networks: {${CONTECO_DC_GLOBAL_NETWORKS}}
volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
