---
version: '3'
services:

# START SERVICE docs.overview
  docs:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.${CONTECO_DC_GLOBAL_IMAGE_NAME}
    environment: [${CONTECO_DC_DOCS_ENVIRONMENT}]
    command: [${CONTECO_DC_DOCS_COMMAND}]
    volumes: [${CONTECO_DC_DOCS_VOLUMES}]
    ports: [${CONTECO_DC_DOCS_PORTS}]
    networks: [${CONTECO_DC_DOCS_NETWORKS}]
    deploy:
      mode: ${CONTECO_DC_DOCS_DEPLOY_MODE}
      replicas: ${CONTECO_DC_DOCS_DEPLOY_REPLICAS}
      resources:
        limits:
          cpus: '${CONTECO_DC_DOCS_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_DOCS_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_DOCS_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_DOCS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${CONTECO_DC_DOCS_DEPLOY_PLACEMENT_CONSTRAINTS}]
      labels: [${CONTECO_DC_DOCS_DEPLOY_LABELS}]
    labels: [${CONTECO_DC_DOCS_LABELS}]
# END SERVICE docs.overview

volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
networks: {${CONTECO_DC_GLOBAL_NETWORKS}}
