---
version: '3'
services:

# START SERVICE docs.overview
  docs:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.${CONTECO_DC_GLOBAL_IMAGE_NAME}
    environment: []
    command: ['usleep 500000000']
    volumes: []
    ports: []
    networks: []
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '0.75'
          memory: '128m'
        reservations:
          cpus: '0.0'
          memory: '5m'
      labels: [${CONTECO_DC_DOCS_OVERVIEW_DEPLOY_LABELS}]
# END SERVICE docs.overview

volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
networks: {${CONTECO_DC_GLOBAL_NETWORKS}}
